require:
- rubocop-performance
- rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - has_jwt_token.gemspec
    - spec/**/*.rb

Naming/PredicateName:
  Enabled: true
  AllowedMethods:
    - has_jwt_token

Style/Documentation:
  Enabled: false
